name: Chrome Testing

on: [push]

jobs:
  Functional-Test-Chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create isolated
        
      - name: Deploy AUT
        run: docker build -t aut-image . && docker run --network=isolated -d -p 80:80 --name docker-apache aut-image
        
      - name: Get AUT URL
        run: |
          URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV
          
      - name: Check AUT Url
        run: curl ${{ env.URL }}

      # Menggunakan image Selenium khusus Chrome
      - name: Selenium Preparation Chrome
        run: docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name chrome-standalone selenium/standalone-chrome:latest

      - name: Wait for Selenium Hub
        run: sh wait.sh

      - name: Check the Hub
        run: curl http://localhost:4444/ui

      - name: Install Selenium client
        run: pip install -U selenium

      # Memanggil script Python khusus Chrome
      - name: Run test
        run: python tests/hello_chrome.py ${{ env.URL }}

      # Mengupload hasil jepretan Chrome
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenium-screenshot-chrome
          path: screenshot_chrome.png

      - name: stop docker
        run: docker stop docker-apache